{% set name = "git-annex-remote-googledrive" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db7d01be1701407e3d3e079e87a266e9e091510538e691f02fc4ab2c50f15fac

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - annexremote
    - pydrive
    - python >=3
    - tenacity

test:
  commands:
    - git-annex-remote-googledrive version

about:
  home: https://github.com/Lykos153/git-annex-remote-googledrive
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: git annex special remote for Google Drive
  doc_url: https://github.com/Lykos153/git-annex-remote-googledrive
  dev_url: https://github.com/Lykos153/git-annex-remote-googledrive

extra:
  recipe-maintainers:
    - notestaff
