travis:
  secure:
    BINSTAR_TOKEN: A47Nzm/Sbg3+0pjT8/qIBBo9628VVabNmTLcX58ImUI3jFWDdi/C01Pwxfmn8MSRBIaU6eJT7XArjk8MqrA6Qh8oYbNd41m+1h+UIaQbTt+zdrvtnFDg+AqofQlaBkLLNmIVyf9RgeYdOtUsWvcjbl3zzUxZZAbNiPOJTW2BZdl27MG9PiTIVklo8V9chGXrTJA244D4wVnT3Ala6VXnBWWOYregQ4YYCxbhxl0w5EZtxvTz6cJndqvZ7KOwbf6PvX1WZTsp5xrVfxvXDIRHlQer4wwA9/NO6et+hS5qp/R2Q6BXjOzBU7l54PIuPmOeLMHiuYUIpPuo6gbzzecGbpWVq93ZBIp9wDBv/5IvRzdZE6FS9D0gEKfpobsb9XgJRJDp78AXOiWqGo0NZjrt1XuuKVTojZVCa0hX0bB9Eoa0UNkafzJMQFeufj1/doFZo9VvSmeoVIA+ycmE3B4mgz6ElbY06m8rd7LGGk+YrsVmXgZMrevG44CzALV6oNACE9ayGXeA8KmCBGZItjLrRPpXBriSwxUVtQeNSnuPTssbvZxmXakRmZus13QIVdOnLT2SD0NKm9oTyq0pQomp/PALTwyfDBp5aYsygBX5+FW6GYgtkAuhFzjMlYtfZja5n07eG2dWjV93rTYlgsmVY5WkdQevZY5NGsJkVHPhytM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
